### PR TITLE
Display offices alphabetically

### LINKED ISSUE #78: office list - sorting
should the office list be sorted alphabetically? Would make it much easier to find your office

### PR DESCRIPTION
**Pull request by blakegong**
## Description

Display offices alphabetically in all the related dropdowns.

## References

Closes #78.

## CCs

@rshokrizadeh @dineshsaravanan @shiyunl 

## Risks

Low, `offices` query related features might be affected.

### CODE REVIEW

**Comment by liulikun** [comment]
Doesn't seem we have a descending sort case. Might be better just sort by ascending by default instead of passing the sort order around.

**Comment by blakegong** [comment]
@liulikun I personally would prefer the `sortBy` approach 😄 The thinking is:

1. Adding one more argument to `offices` query is still very cheap
1. Normally for any resource, people would expect things to be returned in the order of ID, and I'm keen to keep that
1. We might have an advanced office management page in the future, where sorting by any attribute might be needed. I felt like keeping this `sortBy` parameter should be the best option going forward

**Comment by blakegong** [comment]
Thanks for the suggestion @liulikun! Please give this PR a go again 🙇

**Comment by liulikun** [comment]
👍

**Comment by blakegong** [comment]
@liulikun if all good, could you please drop an approval to make this PR mergeable? Or let me know what else is needed. Thank you! 🙇

**Review by liulikun — APPROVED** [review]

**Pull request merged**
