### PR TITLE
add redux devtools for easier state debugging

### PR DESCRIPTION
**Pull request by nchieng**
Prefer using the browser extension to inspect state than following the output on console

### CODE REVIEW

**Review by craig-day — APPROVED** [review]
Assuming this can't blowup with some undefined error, looks good to me

**Comment by nchieng** [comment]
I have not experienced any issues on Central Admin.

And it is restricted to dev.

I've just tested this successfully with a few different browsers with and without the Redux Devtool extension.

**Comment by craig-day** [comment]
@nchieng do you still want to merge this?

**Comment by nchieng** [comment]
I don't see any harm in doing so.
However, given how old this PR is, I think it is better to close it without merging.
If there are other contributors that find that they are missing this, it would be easier to dredge this back up.

**Comment by craig-day** [comment]
Okay, closing for now. Thanks!

**Pull request closed without merging**
