### PR TITLE
Add i18n devtools

### PR DESCRIPTION
**Pull request by Pancrisp**
## Description

Adding this to help with validating translation keys as suggested in https://github.com/zendesk/volunteer_portal/pull/222#issuecomment-541214605

cc @daphnechou 

## Risks (if any)
Low - new gem for validating translation keys

### CODE REVIEW

**Comment by Pancrisp** [comment]
Welp, can someone help with adding the Artifactory ENV vars into our CircleCI config?

**Review by daphnechou — APPROVED** [review]
Team adding the i18n validation gem 
cc @ovillegaszen @hanli625

**Review by craig-day — CHANGES_REQUESTED** [review]
This is an open source project, so we cannot add any private zendesk gems to it.

**Comment by daphnechou** [comment]
> This is an open source project, so we cannot add any private zendesk gems to it.

**Comment by dadah89** [comment]
@daphnechou for now, developers can install the gem in their machines and run validation locally before committing code

**Comment by daphnechou** [comment]
@Pancrisp Please Igor's comment. I guess we can close this PR.

**Comment by samzx** [comment]
@ovillegaszen we'll get the validations set up locally to avoid https://github.com/zendesk/volunteer_portal/pull/222 in the future

**Pull request closed without merging**
