### PR TITLE
[LOCAL-44] Strings: reverse sweep (auto)

### PR DESCRIPTION
**Pull request by string-sweep**
NOTE: String Sweep will be suspended for this repo until this PR is merged or closed!

/cc @zendesk/volunteer @zendesk/localization @zendesk/i18n-dev
### Risks
Low. English edits and title improvements.

### CODE REVIEW

**Comment by damiann** [comment]
Fixes a lot of node leaf issues with keys ([more info](https://zendesk.atlassian.net/wiki/spaces/globalization/pages/742233220/Translation+Node+Leaf+Issue)). Would be helpful to add validation from https://github.com/zendesk/zendesk_i18n_dev_tools

**Review by daphnechou — APPROVED** [review]

**Comment by daphnechou** [comment]
@ovillegaszen @samzx Please see Damian's comment. THX

**Review by Pancrisp — APPROVED** [review]
Thanks for this 👍 

@samzx We should consider Damian's suggestion, it has helped me a lot working with translation strings in Lotus. I'll open a PR for it.

**Comment by samzx** [comment]
cc @ovillegaszen we'll have to replace the keys in the code, I'll have a PR up for that soon.

**Pull request merged**
